### ISSUE TITLE
Devtools breaks app

### ISSUE THREAD

**Issue by bravecow** [RedHatter/svelte-devtools#22]
Unknown root component:

![image](https://user-images.githubusercontent.com/988471/69907143-6cf3c480-13d8-11ea-88c5-a00d33e406cf.png)

Console error:

![image](https://user-images.githubusercontent.com/988471/69907157-88f76600-13d8-11ea-9746-5b9f0e3435f2.png)

code: https://github.com/bravecow/svelte-devtools-issue
1. yarn
2. yarn watch (for building JS)
3. yarn start (for SSR)

Thanks.

**Comment by RedHatter** [comment]
An internal changed in Svelte 3.14 broke devtools. The recently released svelte-devtools 1.2.0 (approved in the chrome store today) should fix this issue.

**Comment by bravecow** [comment]
Something is still broken with brackets or SVG icon:

<img width="1116" alt="Screenshot 2019-12-01 at 18 25 04" src="https://user-images.githubusercontent.com/988471/69916781-eab2e100-1467-11ea-9020-b6df4f9cf08a.png">

Code:

<img width="512" alt="Screenshot 2019-12-01 at 18 23 10" src="https://user-images.githubusercontent.com/988471/69916744-a8899f80-1467-11ea-856d-75ca985c1874.png">

Also both chips are childs of `FilterDropdown` component. The source is the same by link before.

**Comment by bravecow** [comment]
And another JS error that breaks app till I remove Svelte Dev tools is:

![image](https://user-images.githubusercontent.com/988471/69916922-842ec280-1469-11ea-9912-e5c578a0bfcf.png)

(after project build open first dropdown and select some chips).

**Comment by RedHatter** [comment]
Thank you for the bug report! Both issues should be fixed in version 1.2.1. It's currently under review but you should see it in the respective stores within a few days.

**Comment by bravecow** [comment]
Thanks for the great work!
